name: Build and Publish DSLink Dart InfluxDB

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Get dependencies
        run: dart pub get

      - name: Build DSLink binary
        run: |
          dart compile exe bin/dslink.dart -o bin/dslink

      - name: Build Docker image with version tag
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | awk '{print $2}')
          docker build -t dslink-dart-influxdb:$VERSION .

      - name: Publish Docker image to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker tag dslink-dart-influxdb:$VERSION $DOCKER_USERNAME/dslink-dart-influxdb:$VERSION
          docker push $DOCKER_USERNAME/dslink-dart-influxdb:$VERSION

      - name: Upload DSLink binary as artifact
        uses: actions/upload-artifact@v3
        with:
          name: dslink-binary
          path: bin/dslink

      - name: Get version from pubspec.yaml
        id: get_version
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | awk '{print $2}')
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Create Release
        if: github.ref == 'refs/heads/main'
        uses: gh actions/create-release@v1
        with:
          tag_name: ${{ env.version }}
          release_name: ${{ env.version }}
          body: "Release for version ${{ env.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload DSLink binary to release
        if: github.ref == 'refs/heads/main'
        uses: gh actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/dslink
          asset_name: dslink-dart-influxdb-linux
          asset_content_type: application/octet-stream
